import type { RecommendationSuccess } from '@/lib/recommend/types';

/** Build mailto URL for emailing results (opens default mail client). */
export function buildRecommendationMailto(
  email: string,
  resp: RecommendationSuccess,
  shareUrl: string
): string {
  const s = resp.summary;
  const top = resp.picks;

  const lines: string[] = [];

  lines.push('Your Racket IQ recommendation');
  lines.push('===============================');
  lines.push('');
  lines.push(`PLAYER TYPE: ${resp.persona.label}`);
  lines.push(resp.persona.blurb);
  lines.push('');
  lines.push('YOUR PROFILE');
  lines.push(`Height ${s.heightIn}" · Weight ${s.weightLb} lb · Grip L${s.gripIdx}`);
  lines.push(
    `Level: ${s.level}${s.utr != null ? ` · UTR ${s.utr}` : ''}${s.usta != null ? ` · USTA ${s.usta}` : ''}`
  );
  lines.push(`Swing: ${s.swing} · Style: ${s.style} · Volley: ${s.volleyLabel}`);
  lines.push(
    `Budget: ${s.budget >= 999 ? 'no limit' : `≤ $${s.budget}`} · Arm-friendly only: ${s.arm === 'Yes' ? 'yes' : 'no'}`
  );
  lines.push(`String preference: ${s.stringPref}`);
  if (s.notesText.trim()) lines.push(`Notes: ${s.notesText.trim()}`);
  if (s.parsedTags?.length)
    lines.push(`(detected: ${s.parsedTags.join(' · ')})`);
  lines.push(`Target frame weight: ${s.targetWeight.toFixed(1)} oz`);
  if (resp.relaxations.length) {
    lines.push('');
    lines.push(`Note: ${resp.relaxations.join(' · ')}`);
  }
  lines.push('');
  lines.push('TOP 3 RECOMMENDATIONS');
  lines.push('=====================');

  top.forEach((pick, i) => {
    const r = pick.racket;
    const str = pick.string;
    const rank = i === 0 ? '★ #1 TOP COMBO' : `#${i + 1}`;
    lines.push('');
    lines.push(
      `${rank}: ${r.Brand} ${r.Model} (${r.Year})  —  $${r.Price_USD}  ·  Match ${pick.matchScore}/100`
    );
    lines.push(
      `  Specs: ${r.Weight_Strung_oz.toFixed(1)} oz · ${r.Head_Size_sqin}" head · ${r.String_Pattern} · ${r.Balance_pts} · SW ${r.Swingweight} · RA ${r.Stiffness_RA} · ${r.Frame_Type}`
    );
    lines.push(`  Why: ${pick.why}`);
    lines.push(`  Tags: ${pick.tags.join(', ')}`);
    if (str && pick.buyStringUrl) {
      lines.push(
        `  String: ${str.Brand} ${str.Model} (${str.String_Type}) — ${str.Gauge_Name} gauge at ${pick.tension} lb`
      );
      lines.push(`  Buy racket: ${pick.buyRacketUrl}`);
      lines.push(`  Buy string: ${pick.buyStringUrl}`);
    } else {
      lines.push(`  Buy racket: ${pick.buyRacketUrl}`);
    }
  });

  lines.push('');
  lines.push('───');
  lines.push('Generated by Racket IQ');
  lines.push('https://kedarsnd-ai.github.io/racket-recommender/');
  lines.push('');
  lines.push('Share this exact recommendation:');
  lines.push(shareUrl);

  const subject = `Your Racket IQ recommendation — ${top[0].racket.Brand} ${top[0].racket.Model}`;
  return `mailto:${encodeURIComponent(email.trim())}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join('\n'))}`;
}
